version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - SIP_TRUNK_ID=${SIP_TRUNK_ID}
    volumes:
      - .:/app
